# Generated by Django 5.1.2 on 2025-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_taskjoinrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_status",
        ),
    ]
